spring.datasource.url=jdbc:sqlanywhere:Host=181.222.138.93:2638;DatabaseName=contabil
spring.datasource.username=EXTERNO
spring.datasource.password=12345
spring.datasource.driver-class-name=sap.jdbc4.sqlanywhere.IDriver
